version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '22:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    rebase-strategy: auto
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'

      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'

      jest:
        patterns:
          - 'jest'
          - 'jest-*'

      # Add NX packages group
      nx:
        patterns:
          - '@nx/*'
          - 'nx'

      # Add Next.js packages group
      next:
        patterns:
          - 'next'
          - 'next-*'
          - '@next/*'
          - 'eslint-config-next'

      # Add NestJS packages group
      nest:
        patterns:
          - '@nestjs/*'

      react:
        patterns:
          - 'react'
          - 'react-dom'

      react-dnd:
        patterns:
          - 'react-dnd'
          - 'react-dnd-*'

      redux:
        patterns:
          - '@reduxjs/toolkit'
          - 'react-redux'

      richtext-editor:
        patterns:
          - 'markdown-it'
          - 'markdown-it-*'

      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'

      testing-library:
        patterns:
          - '@testing-library/*'

      webpack:
        patterns:
          - 'webpack'
          - 'webpack-cli'
          - 'webpack-dev-server'

    labels:
      - 'source: dependencies'
      - 'pr: chore'
    reviewers:
      - 'matt.mencel'
    ignore:
      # Only allow patch as minor babel versions need to be upgraded all together
      - dependency-name: '@babel/*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

      - dependency-name: '*'
        update-types:
          - 'version-update:semver-patch'
          - 'version-update:semver-major'

  # Add security-focused configuration
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    groups:
      security-critical:
        patterns:
          - 'axios'
          - 'jsonwebtoken'
          - 'express'
    labels:
      - 'source: dependencies'
      - 'security'

  - package-ecosystem: github-actions
    open-pull-requests-limit: 0
    directory: /
    commit-message:
      prefix: 'chore'
      include: 'scope'
    schedule:
      interval: weekly
      day: sunday
      time: '22:00'
    labels:
      - 'source: dependencies'
      - 'pr: chore'

  # Add Docker configuration
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
