version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      rails:
        patterns:
          - "rails"
          - "turbo-rails"
          - "stimulus-rails"
          - "importmap-rails"
          - "tailwindcss-rails"
          - "propshaft"
          - "jbuilder"
          - "solid_cache"
          - "solid_queue"
          - "solid_cable"
          - "bootsnap"
          - "tzinfo-data"
      authentication:
        patterns:
          - "devise"
          - "devise-jwt"
          - "pundit"
          - "omniauth*"
      api:
        patterns:
          - "jsonapi-serializer"
          - "kaminari"
          - "rack-attack"
          - "rswag*"
      monitoring:
        patterns:
          - "statsd-instrument"
          - "dogstatsd-ruby"
          - "bullet"
      development-tools:
        patterns:
          - "web-console"
          - "debug"
          - "dotenv-rails"
          - "brakeman"
          - "rubocop*"
          - "solargraph"
          - "kamal"
          - "thruster"
          - "dockerfile-rails"
      test:
        patterns:
          - "rspec-rails"
          - "factory_bot_rails"
          - "faker"
          - "cucumber*"
          - "capybara"
          - "selenium-webdriver"
          - "shoulda-matchers"
          - "database_cleaner-active_record"
          - "capybara-playwright-driver"
          - "email_spec"
          - "timecop"
      storage:
        patterns:
          - "active_storage_validations"
          - "image_processing"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
