---
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^(deploy/helm/|config/cucumber\.yml)
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.29
    hooks:
      - id: helmlint

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.2.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: rubocop
        name: Rubocop
        entry: bundle exec rubocop
        language: system
        types: [ruby]
        files: \.rb$
        additional_dependencies: []
      - id: brakeman
        name: Brakeman
        entry: bundle exec brakeman --no-exit-on-warn --no-pager
        language: system
        pass_filenames: false
        always_run: true
        additional_dependencies: []
