---
inherit_mode:
  merge:
    - Exclude

require:
  - standard

plugins:
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

inherit_from:
  - .rubocop/rspec.yml
  - .rubocop/minitest.yml
  - .rubocop/strict.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - bin/**/*
    - build/**/*
    - config/**/*
    - db/**/*
    - frontend/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
